libname ch5data '/home/u64191330/P4B_st/Chapter 5/Data';
libname ch5res '/home/u64191330/P4B_st/Chapter 5/Results & Code';

/* Exercise 1 */

*a);
PROC PRINT DATA=ch5data.smsales NOOBS N LABEL;
	VAR Invoice_ID Date Total Rating;
	LABEL Invoice_ID = 'Invoice identification number'
		  Date = 'Date of purchase'
		  Total = 'Total price including tax'
		  Rating = 'Customer satisfaction rating';
RUN;

*b);
PROC PRINT DATA=ch5data.smsales NOOBS N LABEL;
	VAR Branch Invoice_ID Date Total Rating;
	LABEL Invoice_ID = 'Invoice identification number'
		  Date = 'Date of purchase'
		  Total = 'Total price including tax'
		  Rating = 'Customer satisfaction rating';
	WHERE Branch = 'A' OR Branch = 'C';
	TITLE 'Listing of Sales Transaction for Branches A and C';
	FOOTNOTE 'Generated by Data Analytics System';
RUN;
TITLE; 
FOOTNOTE;

*c);
* Step 1 - Sort the data by branch;
PROC SORT DATA=ch5data.smsales OUT=ch5data.smsales;
	BY Branch;
RUN;

* Step 2 - Create the report;
OPTIONS NOBYLINE;
PROC PRINT DATA=ch5data.smsales NOOBS;
	VAR City Invoice_ID Date Total Rating;
	WHERE Quantity > 5;
	BY Branch;
	SUM Total Rating;
	TITLE 'Listing of Sales Transaction for Branch #BYVAL(Branch)';
RUN;
OPTIONS BYLINE; 
TITLE;

/* Exercise 2 */

*a);
DATA ch5res.adidas_us_sales1;
	SET ch5data.adidas_us_sales;
	Category_Gender = SUBSTRN(Product, 1, 3);
RUN;

*b);
* Step 1 - Create the format genderf;
PROC FORMAT;
	VALUE $genderf 'Men' = 'Male'
				   'Wom' = 'Women';
RUN;

* Step 2 - Create the format marginf;
PROC FORMAT;
	VALUE marginf low - <0.2 = 'Low'
				   0.2 - <0.4 = 'Medium'
				   0.4 - <0.6 = 'High'
				   0.6 - high = 'Very High';
RUN;

* Step 3 - Generate the report;
PROC PRINT DATA=ch5res.adidas_us_sales1;
	VAR Retailer Invoice_Date Category_Gender Operating_Margin;
	FORMAT Category_Gender $genderf. Operating_Margin marginf.;
RUN;

/* Exercise 3 */
* Step 1 - Sort the data set;
PROC SORT DATA=ch5data.sales OUT=sales;
	BY Region;
RUN;

* Step 2 - Create the report;
PROC PRINT DATA=sales;
	VAR Quantity TotalSales;
	BY Region;
	ID Region; * Adds the Region as a column in the left and surpresses NOOBS;
	SUM Quantity TotalSales;
	TITLE 'Sales FIgures from the SALES Data Set';
RUN;
TITLE;
